wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717406892
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      3:
      - 19
      - 23
      4: 3.10.12
      5: 0.17.0
      6: 4.41.1
      8:
      - 1
      - 5
      - 12
      13: linux-x86_64
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 32
patch_size:
  desc: null
  value: 16
embed_dim:
  desc: null
  value: 384
num_classes_list:
  desc: null
  value:
  - 3
  - 11
  - 2
  - 2
  - 7
  - 2
  - 8
